"""OpenCore release handling: download, base EFI layout, bundled utilities.

    root = opcoremgr.dw()                      # latest release
    root = opcoremgr.dw(version="1.0.7")
    root = opcoremgr.dw("https://github.com/acidanthera/OpenCorePkg/releases/download/1.0.7/OpenCore-1.0.7-RELEASE.zip")
"""
import os
import platform
import re
import shutil
import subprocess
from pathlib import Path

from scripts import kextmgr

REPO = "acidanthera/OpenCorePkg"


def dw(url=None, version="latest", info=None):
    """Download an OpenCore RELEASE zip and return the unpacked folder.

    `info`: optional dict, filled with the archive name and its SHA-256.
    """
    if url is None and version != "latest":
        url = f"https://github.com/{REPO}/releases/download/{version}/OpenCore-{version}-RELEASE.zip"
    elif url is None:
        rel = kextmgr.gh_release(REPO, version)
        url, _ = kextmgr.pick_asset(rel, r"^OpenCore-.*-RELEASE\.zip$")
    elif not url.endswith(".zip"):
        raise ValueError("OpenCore ships as a release zip (OpenCore.efi, drivers, Sample.plist, "
                         "ocvalidate, macserial all come from it) - pass the OpenCore-X.Y.Z-RELEASE.zip URL")
    archive = kextmgr.fetch(url)
    if info is not None:
        info["asset"] = archive.name
        info["sha256"] = kextmgr.sha256(archive)
    root = kextmgr.extract(archive)
    if not (root / "X64" / "EFI" / "OC" / "OpenCore.efi").is_file():
        raise RuntimeError(f"{url} doesn't look like an OpenCore release zip")
    return root


def version(root):
    m = re.search(r"OpenCore-(\d+\.\d+\.\d+)", Path(root).name)
    return m[1] if m else "?"


def sample_plist(root):
    return Path(root) / "Docs" / "Sample.plist"


def tool(root, name):
    """Path to a bundled utility (ocvalidate, macserial) built for this OS."""
    suffix = {"Darwin": "", "Linux": ".linux", "Windows": ".exe"}.get(platform.system())
    if suffix is None:
        raise RuntimeError(f"no {name} build for {platform.system()}")
    path = Path(root) / "Utilities" / name / (name + suffix)
    if not path.is_file():
        raise RuntimeError(f"{name} not found in {root}")
    if os.name != "nt":
        path.chmod(0o755)
    return path


def install_base(root, efi, drivers, tools):
    """Lay out EFI/BOOT and EFI/OC with OpenCore, the given drivers and tools."""
    src = Path(root) / "X64" / "EFI"
    efi = Path(efi)
    for sub in ("BOOT", "OC/ACPI", "OC/Drivers", "OC/Kexts", "OC/Tools", "OC/Resources"):
        (efi / sub).mkdir(parents=True, exist_ok=True)
    shutil.copy2(src / "BOOT" / "BOOTx64.efi", efi / "BOOT" / "BOOTx64.efi")
    shutil.copy2(src / "OC" / "OpenCore.efi", efi / "OC" / "OpenCore.efi")
    for d in drivers:
        shutil.copy2(src / "OC" / "Drivers" / d, efi / "OC" / "Drivers" / d)
    for t in tools:
        shutil.copy2(src / "OC" / "Tools" / t, efi / "OC" / "Tools" / t)


def macserial(root, model):
    """(serial, board serial) for an SMBIOS model, generated by the bundled macserial."""
    out = subprocess.run([str(tool(root, "macserial")), "-m", model, "-n", "1"],
                         capture_output=True, text=True, check=True).stdout
    m = re.search(r"^\s*(\w{10,})\s*\|\s*(\w{10,})\s*$", out, re.M)
    if not m:
        raise RuntimeError(f"unexpected macserial output for {model}: {out.strip()!r}")
    return m[1], m[2]
